# rpmrebuild autogenerated specfile

BuildRoot: /rpmbuild/
AutoProv: no
%undefine __find_provides
AutoReq: no
%undefine __find_requires
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0
#dummy
#dummy
#BUILDHOST:    linux-pc.fios-router.home
#BUILDTIME:    Thu Oct 15 14:17:31 2020
#SOURCERPM:    Ice-6.0.8-1.src.rpm

#RPMVERSION:   4.15.1



#OS:           linux
#SIZE:           5351833
#ARCHIVESIZE:           5354420
#ARCH:         x86_64
BuildArch:     x86_64
Name:          Ice
Version:       6.0.8
Release:       1
License:       GPLv2 
Group:         default
Summary:       Tool to create Chromium/Chrome/Firefox/Vivaldi SSBs in Peppermint OS Ported to Fedora
URL:           https://github.com/peppermintos/ice
Vendor:        Peppermint OS Developers
Packager:      <TheLinuxKid>





Prefix:        /
Provides:      ice = 1.0-1
Provides:      ice(x86-64) = 1.0-1
#Requires:      rpmlib(CompressedFileNames) <= 3.0.4-1
#Requires:      rpmlib(PayloadFilesHavePrefix) <= 4.0-1





%description
Application to easily add and remove Chromium site specific browsers in Debian and Ubuntu based Linux distributions. It was originally created for Peppermint OS Ice and is now used as the default SSB application in Peppermint OS since the two branches of the OS merged for Peppermint Two. Since version 5, Ice has supported Google Chrome. Ice now supports Chrome, Chromium, Firefox, and Vivaldi. Chrome, Chromium, and Vivaldi SSB's can now be completely isolated from each other (or use the shared master browser profile) Firefox SSB's are always isolated.
%files
%attr(0775, root, root) "/rpmbuild/SOURCES/usr/bin/ice"
%attr(0775, root, root) "/rpmbuild/SOURCES/usr/bin/ice-firefox"
%attr(0664, root, root) "/rpmbuild/SOURCES/usr/lib/peppermint/ice/ice.glade"
%attr(0664, root, root) "/rpmbuild/SOURCES/usr/lib/peppermint/ice/places.sqlite"
%attr(0664, root, root) "/rpmbuild/SOURCES/usr/lib/peppermint/ice/search.json.mozlz4"
%attr(0664, root, root) "/rpmbuild/SOURCES/usr/share/applications/ice.desktop"
%attr(0664, root, root) "/rpmbuild/SOURCES/usr/share/ice/locale/fr/LC_MESSAGES/messages.po"
%attr(0664, root, root) "/rpmbuild/SOURCES/usr/share/ice/locale/ja/LC_MESSAGES/messages.po"
%attr(0664, root, root) "/rpmbuild/SOURCES/usr/share/ice/locale/messages.pot"
%attr(0664, root, root) "/rpmbuild/SOURCES/usr/share/ice/locale/nl/LC_MESSAGES/messages.po"
%attr(0664, root, root) "/rpmbuild/SOURCES/usr/share/ice/locale/pl/LC_MESSAGES/messages.po"
%attr(0664, root, root) "/rpmbuild/SOURCES/usr/share/ice/locale/pt_BR/LC_MESSAGES/messages.po"
%attr(0664, root, root) "/rpmbuild/SOURCES/usr/share/ice/locale/pt_PT/LC_MESSAGES/messages.po"
%attr(0664, root, root) "/rpmbuild/SOURCES/usr/share/ice/locale/sv/LC_MESSAGES/messages.po"
%attr(0664, root, root) "/rpmbuild/SOURCES/usr/share/ice/locale/zh_CN/LC_MESSAGES/messages.po"
%attr(0664, root, root) "/rpmbuild/SOURCES/usr/share/pixmaps/ice.png"








%changelog

